# Generated by Django 3.2 on 2022-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesheet',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tradesheet',
            name='profit_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tradesheet',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
    ]
