# Generated by Django 3.2 on 2022-11-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0002_auto_20221112_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradesheet',
            options={'verbose_name': 'Trading Sheet'},
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='profit_loss',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
