# Generated by Django 3.2 on 2022-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0003_auto_20221126_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesheet',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
