# Generated by Django 3.2 on 2022-11-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0004_alter_tradesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesheet',
            name='buy_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='no_of_shares',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='sell_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='symbol',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
