# Generated by Django 3.2 on 2022-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0005_auto_20221126_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesheet',
            name='buy_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='no_of_shares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='profit_loss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='sell_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tradesheet',
            name='symbol',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
