# Generated by Django 3.2 on 2022-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSheet', '0007_auto_20221128_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradesheet',
            options={'ordering': ('-date',), 'verbose_name': 'Trading Sheet'},
        ),
        migrations.AddField(
            model_name='tradesheet',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
